### PR TITLE
Update compatibility with Nette 3.0

### PR DESCRIPTION
**Pull request by PavelJurasek**

### CODE REVIEW

**Comment by akadlec** [comment]
Failing tests and dependency on RC is not good.

**Comment by PavelJurasek** [comment]
Yes, stable release is out so the dependencies are updated. Travis build was cleaned up as well.

**Review by akadlec — APPROVED** [review]

**Comment by wessnice** [comment]
Can you bump the version on packagist as well, please? Thank you :)

**Comment by akadlec** [comment]
@wessnice done.

**Pull request merged**
